language: node_js
node_js:
  - '8'
  - '6'
script:
  - npm run lint
  - npm run coveralls
  - npm run build
branches:
  only:
    - master
cache:
  directories:
  - node_modules
before_install:
- npm update
install:
- npm install
